apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sample-app-netpol
  namespace: sample-app
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring   # Prometheus scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system  # Traefik ingress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system  # DNS
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
